### ISSUE TITLE
Clarify function of mfa_supported

### ISSUE THREAD

**Issue by dschulten** [jaredhanson/draft-oauth-mfa#1]
The client can indicate that it supports mfa. What does the authorization server do with that information, or more generally, why was mfa_supported introduced?

It probably allows the server to distinguish if a client can handle mfa at all, but what would the server do with that information? If mfa is required, it will certainly return an mfa_token response regardless of mfa_supported. Only requiring mfa for clients which support it and skipping it for others would not increase security.

What comes to mind is that the authorization server could offer a UI to opt-in to mfa authorizations if mfa is optional and a client indicates that it supports mfa. Was that the idea?

**Comment by jaredhanson** [comment]
I've revised the spec to clarify this functionality, refer to section `2.2.1.  MFA Challenge Request`.

The intent is to allow the server to respond (if it can) with an MFA challenge that the client supports.  For example, say a user has OTP and out-of-band authenticators registered.  If a client only supports OTP (or vice versa), it behooves everyone that the server respond with the OTP challenge.

**Comment by dschulten** [comment]
solved, thank you!
